<?php
/** IRONCORE Gym Management Service: centralized database operations. */
require_once __DIR__ . '/../config/database.php';
class GymManagementService {
 private PDO $db;
 public function __construct(){ $this->db=Database::getInstance(); }
 public function members(string $search='',string $status=''):array{
  $sql="SELECT m.id,m.user_id,m.phone,m.join_date,m.dob,u.full_name,u.email,u.status,s.id subscription_id,s.start_date,s.end_date,s.status subscription_status,p.title plan_title,p.price plan_price FROM members m JOIN users u ON u.id=m.user_id LEFT JOIN subscriptions s ON s.member_id=m.id AND s.id=(SELECT MAX(s2.id) FROM subscriptions s2 WHERE s2.member_id=m.id) LEFT JOIN membership_plans p ON p.id=s.plan_id WHERE 1=1";$params=[];
  if($search!==''){$sql.=" AND (u.full_name LIKE :q OR u.email LIKE :q OR m.phone LIKE :q)";$params['q']="%$search%";} if($status!==''){$sql.=" AND u.status=:status";$params['status']=$status;}$sql.=" ORDER BY m.id DESC";$s=$this->db->prepare($sql);$s->execute($params);return $s->fetchAll();
 }
 public function createMember(array $d):int{$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO users(full_name,email,password_hash,role,status) VALUES(:name,:email,:pass,'member','active')");$s->execute(['name'=>trim($d['name']),'email'=>strtolower(trim($d['email'])),'pass'=>password_hash($d['password']??'Member@123',PASSWORD_BCRYPT)]);$uid=(int)$this->db->lastInsertId();$s=$this->db->prepare("INSERT INTO members(user_id,phone,emergency_contact,gender,dob,address,join_date) VALUES(:uid,:phone,:emergency,:gender,:dob,:address,:join_date)");$s->execute(['uid'=>$uid,'phone'=>$d['phone']??null,'emergency'=>$d['emergency_contact']??null,'gender'=>$d['gender']??null,'dob'=>$d['dob']??null,'address'=>$d['address']??null,'join_date'=>$d['join_date']??date('Y-m-d')]);$mid=(int)$this->db->lastInsertId();if(!empty($d['plan_id'])){$plan=$this->getPlan((int)$d['plan_id']);if($plan){$start=$d['start_date']??date('Y-m-d');$end=date('Y-m-d',strtotime($start.' + '.max(1,(int)$plan['duration_days']).' days'));$s=$this->db->prepare("INSERT INTO subscriptions(member_id,plan_id,start_date,end_date,status) VALUES(:member,:plan,:start,:end,'active')");$s->execute(['member'=>$mid,'plan'=>$plan['id'],'start'=>$start,'end'=>$end]);}}$this->db->commit();return $mid;}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function updateMember(int $id,array $d):void{$s=$this->db->prepare("SELECT user_id FROM members WHERE id=:id");$s->execute(['id'=>$id]);$uid=(int)$s->fetchColumn();if(!$uid)throw new RuntimeException('Member not found');$this->db->beginTransaction();try{$s=$this->db->prepare("UPDATE users SET full_name=:name,email=:email,status=:status WHERE id=:uid AND role='member'");$s->execute(['name'=>trim($d['name']),'email'=>strtolower(trim($d['email'])),'status'=>$d['status']??'active','uid'=>$uid]);$s=$this->db->prepare("UPDATE members SET phone=:phone,emergency_contact=:emergency,gender=:gender,dob=:dob,address=:address WHERE id=:id");$s->execute(['phone'=>$d['phone']??null,'emergency'=>$d['emergency_contact']??null,'gender'=>$d['gender']??null,'dob'=>$d['dob']??null,'address'=>$d['address']??null,'id'=>$id]);$this->db->commit();}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function plans(bool $activeOnly=false):array{$sql="SELECT * FROM membership_plans".($activeOnly?" WHERE status='active'":'')." ORDER BY price ASC";return $this->db->query($sql)->fetchAll();}
 public function getPlan(int $id):?array{$s=$this->db->prepare("SELECT * FROM membership_plans WHERE id=:id");$s->execute(['id'=>$id]);return $s->fetch()?:null;}
 public function savePlan(array $d,?int $id=null):int{$data=['title'=>$d['title'],'tag'=>$d['tag']??null,'price'=>$d['price'],'cycle'=>$d['billing_cycle']??'monthly','days'=>(int)($d['duration_days']??30),'description'=>$d['description']??null,'recommended'=>!empty($d['is_recommended'])?1:0,'status'=>$d['status']??'active'];if($id){$s=$this->db->prepare("UPDATE membership_plans SET title=:title,tag=:tag,price=:price,billing_cycle=:cycle,duration_days=:days,description=:description,is_recommended=:recommended,status=:status WHERE id=:id");$data['id']=$id;$s->execute($data);return $id;}$s=$this->db->prepare("INSERT INTO membership_plans(title,tag,price,billing_cycle,duration_days,description,is_recommended,status) VALUES(:title,:tag,:price,:cycle,:days,:description,:recommended,:status)");$s->execute($data);return(int)$this->db->lastInsertId();}
 public function togglePlan(int $id):void{$s=$this->db->prepare("UPDATE membership_plans SET status=IF(status='active','inactive','active') WHERE id=:id");$s->execute(['id'=>$id]);}
 public function trainers():array{return $this->db->query("SELECT t.*,u.full_name,u.email,u.status FROM trainers t JOIN users u ON u.id=t.user_id ORDER BY t.id DESC")->fetchAll();}
 public function createTrainer(array $d):int{$this->db->beginTransaction();try{$s=$this->db->prepare("INSERT INTO users(full_name,email,password_hash,role,status) VALUES(:name,:email,:pass,'trainer','active')");$s->execute(['name'=>trim($d['name']),'email'=>strtolower(trim($d['email'])),'pass'=>password_hash($d['password']??'Trainer@123',PASSWORD_BCRYPT)]);$uid=(int)$this->db->lastInsertId();$s=$this->db->prepare("INSERT INTO trainers(user_id,specialization,experience_years,bio,hourly_rate) VALUES(:uid,:spec,:exp,:bio,:rate)");$s->execute(['uid'=>$uid,'spec'=>$d['specialization'],'exp'=>(int)($d['experience_years']??0),'bio'=>$d['bio']??null,'rate'=>$d['hourly_rate']??0]);$id=(int)$this->db->lastInsertId();$this->db->commit();return $id;}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function updateTrainer(int $id,array $d):void{$s=$this->db->prepare("SELECT user_id FROM trainers WHERE id=:id");$s->execute(['id'=>$id]);$uid=(int)$s->fetchColumn();if(!$uid)throw new RuntimeException('Trainer not found');$this->db->beginTransaction();try{$s=$this->db->prepare("UPDATE users SET full_name=:name,email=:email,status=:status WHERE id=:uid");$s->execute(['name'=>$d['name'],'email'=>strtolower($d['email']),'status'=>$d['status']??'active','uid'=>$uid]);$s=$this->db->prepare("UPDATE trainers SET specialization=:spec,experience_years=:exp,bio=:bio,hourly_rate=:rate WHERE id=:id");$s->execute(['spec'=>$d['specialization'],'exp'=>(int)$d['experience_years'],'bio'=>$d['bio']??null,'rate'=>$d['hourly_rate']??0,'id'=>$id]);$this->db->commit();}catch(Throwable $e){$this->db->rollBack();throw $e;}}
 public function attendance(string $date=''):array{$date=$date?:date('Y-m-d');$s=$this->db->prepare("SELECT a.*,u.full_name,u.email FROM attendance a JOIN members m ON m.id=a.member_id JOIN users u ON u.id=m.user_id WHERE a.date=:date ORDER BY a.check_in_time DESC");$s->execute(['date'=>$date]);return $s->fetchAll();}
 public function checkIn(int $memberId,string $status='present'):void{$s=$this->db->prepare("SELECT id FROM attendance WHERE member_id=:m AND date=:d");$s->execute(['m'=>$memberId,'d'=>date('Y-m-d')]);if($s->fetchColumn())throw new RuntimeException('Member is already checked in today.');$s=$this->db->prepare("INSERT INTO attendance(member_id,date,check_in_time,status) VALUES(:m,:d,:t,:s)");$s->execute(['m'=>$memberId,'d'=>date('Y-m-d'),'t'=>date('H:i:s'),'s'=>$status]);}
 public function checkOut(int $id):void{$s=$this->db->prepare("UPDATE attendance SET check_out_time=:t WHERE id=:id AND check_out_time IS NULL");$s->execute(['t'=>date('H:i:s'),'id'=>$id]);}
 public function payments():array{return $this->db->query("SELECT p.*,u.full_name FROM payments p JOIN members m ON m.id=p.member_id JOIN users u ON u.id=m.user_id ORDER BY p.payment_date DESC")->fetchAll();}
 public function createPayment(array $d):int{$s=$this->db->prepare("INSERT INTO payments(subscription_id,member_id,amount,payment_method,transaction_id,status) VALUES(:subscription,:member,:amount,:method,:txn,:status)");$s->execute(['subscription'=>$d['subscription_id']??null,'member'=>(int)$d['member_id'],'amount'=>$d['amount'],'method'=>$d['payment_method']??'UPI','txn'=>$d['transaction_id']?:('IRN-'.strtoupper(bin2hex(random_bytes(5)))),'status'=>$d['status']??'paid']);return(int)$this->db->lastInsertId();}
 public function exercises():array{return $this->db->query("SELECT * FROM exercise_catalog ORDER BY category,name")->fetchAll();}
 public function workouts():array{return $this->db->query("SELECT wp.*,u.full_name member_name,tu.full_name trainer_name FROM workout_plans wp JOIN members m ON m.id=wp.member_id JOIN users u ON u.id=m.user_id LEFT JOIN trainers t ON t.id=wp.trainer_id LEFT JOIN users tu ON tu.id=t.user_id ORDER BY wp.id DESC")->fetchAll();}
 public function createWorkout(array $d):int{$s=$this->db->prepare("INSERT INTO workout_plans(member_id,trainer_id,title,goal,start_date,end_date) VALUES(:member,:trainer,:title,:goal,:start,:end)");$s->execute(['member'=>(int)$d['member_id'],'trainer'=>!empty($d['trainer_id'])?(int)$d['trainer_id']:null,'title'=>$d['title'],'goal'=>$d['goal']??null,'start'=>$d['start_date']??date('Y-m-d'),'end'=>$d['end_date']??null]);return(int)$this->db->lastInsertId();}
 public function addWorkoutExercise(array $d):int{$s=$this->db->prepare("INSERT INTO workout_plan_exercises(plan_id,exercise_id,sets,reps,rest_seconds,day_of_week) VALUES(:plan,:exercise,:sets,:reps,:rest,:day)");$s->execute(['plan'=>(int)$d['plan_id'],'exercise'=>(int)$d['exercise_id'],'sets'=>(int)($d['sets']??3),'reps'=>$d['reps']??'10-12','rest'=>(int)($d['rest_seconds']??60),'day'=>$d['day_of_week']??'Mon']);return(int)$this->db->lastInsertId();}
 public function reportStats():array{return['members'=>(int)$this->db->query("SELECT COUNT(*) FROM members")->fetchColumn(),'active_members'=>(int)$this->db->query("SELECT COUNT(*) FROM members m JOIN users u ON u.id=m.user_id WHERE u.status='active'")->fetchColumn(),'trainers'=>(int)$this->db->query("SELECT COUNT(*) FROM trainers t JOIN users u ON u.id=t.user_id WHERE u.status='active'")->fetchColumn(),'plans'=>(int)$this->db->query("SELECT COUNT(*) FROM membership_plans WHERE status='active'")->fetchColumn(),'attendance_today'=>(int)$this->db->query("SELECT COUNT(*) FROM attendance WHERE date=CURDATE()")->fetchColumn(),'revenue'=>(float)$this->db->query("SELECT COALESCE(SUM(amount),0) FROM payments WHERE status='paid' AND MONTH(payment_date)=MONTH(CURDATE()) AND YEAR(payment_date)=YEAR(CURDATE())")->fetchColumn()];}
}
