<?php
require_once __DIR__ . '/../../config/config.php';
require_once __DIR__ . '/../../helpers/security.php';
require_once __DIR__ . '/../../middleware/AdminMiddleware.php';
require_once __DIR__ . '/../../services/SettingsService.php';
AdminMiddleware::handle();
$settings=new SettingsService(); $message=''; $error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!validateCsrfToken($_POST['csrf_token']??null)){$error='Security token expired. Please refresh and try again.';}
  else {try{$settings->save(['gym_name'=>$_POST['gym_name']??'IRONCORE Fitness','contact_email'=>$_POST['contact_email']??'','phone'=>$_POST['phone']??'','address'=>$_POST['address']??'','currency'=>$_POST['currency']??'INR','timezone'=>$_POST['timezone']??'Asia/Kolkata']);$message='Settings saved successfully.';}catch(Throwable $e){$error=APP_DEBUG?$e->getMessage():'Unable to save settings.';}}
}
$s=array_merge(['gym_name'=>'IRONCORE Fitness','contact_email'=>'','phone'=>'','address'=>'','currency'=>'INR','timezone'=>'Asia/Kolkata'],$settings->all());
$name=$_SESSION['full_name']??'System Admin';
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"><title>System Settings | IRONCORE</title><link rel="stylesheet" href="/assets/css/style.css"><link rel="stylesheet" href="/assets/css/dashboard.css"><link rel="stylesheet" href="/assets/css/responsive.css"></head>
<body style="background-color:var(--color-bg)"><div class="dashboard-shell"><div class="sidebar-overlay"></div><aside class="sidebar"><div class="sidebar-brand"><a href="/index.php" class="brand-logo"><svg class="logo-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M6.5 6.5h11M6.5 17.5h11M4 10h16M4 14h16M2 6v12M22 6v12"/></svg><span>IRONCORE</span></a><span class="sidebar-badge">ADMINISTRATOR CONTROL</span></div><ul class="sidebar-nav"><li><a href="/admin/index.php" class="nav-item-link">Dashboard</a></li><li><a href="/admin/members.php" class="nav-item-link">Members</a></li><li><a href="/admin/trainers.php" class="nav-item-link">Trainers</a></li><li><a href="/admin/memberships.php" class="nav-item-link">Memberships</a></li><li><a href="/admin/attendance.php" class="nav-item-link">Attendance</a></li><li><a href="/admin/payments.php" class="nav-item-link">Payments</a></li><li><a href="/admin/workouts.php" class="nav-item-link">Workouts</a></li><li><a href="/admin/reports.php" class="nav-item-link">Reports</a></li></ul><div class="sidebar-footer"><div class="user-profile-badge"><div class="avatar-circle"><?=e(strtoupper(substr($name,0,1)))?></div><div class="user-info"><div class="user-name"><?=e($name)?></div><div class="user-role">Super Admin</div></div></div><a href="/logout.php" class="btn btn-primary" style="width:100%;justify-content:center">Logout</a></div></aside>
<div class="main-wrapper"><header class="dashboard-header"><div class="header-title-group"><h1>SYSTEM SETTINGS</h1><p>Configure the gym identity and operational defaults.</p></div></header><main class="dashboard-body"><section class="panel-card" style="max-width:900px;margin:0 auto;padding:2rem"><h2 style="margin-bottom:.5rem">Gym Configuration</h2><p style="color:var(--color-text-muted);margin-bottom:1.5rem">These settings are stored in MySQL and can be changed without editing application files.</p><?php if($message):?><div class="status-pill active" style="margin-bottom:1rem;display:inline-block"><?=e($message)?></div><?php endif;?><?php if($error):?><div class="status-pill danger" style="margin-bottom:1rem;display:inline-block"><?=e($error)?></div><?php endif;?><form method="post" style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:1rem"><input type="hidden" name="csrf_token" value="<?=e(generateCsrfToken())?>"><label>Gym Name<input name="gym_name" value="<?=e($s['gym_name'])?>" required></label><label>Contact Email<input type="email" name="contact_email" value="<?=e($s['contact_email'])?>"></label><label>Phone<input name="phone" value="<?=e($s['phone'])?>"></label><label>Currency<select name="currency"><option value="INR" <?=$s['currency']==='INR'?'selected':''?>>INR (₹)</option><option value="USD" <?=$s['currency']==='USD'?'selected':''?>>USD ($)</option><option value="EUR" <?=$s['currency']==='EUR'?'selected':''?>>EUR (€)</option></select></label><label>Timezone<select name="timezone"><option value="Asia/Kolkata" <?=$s['timezone']==='Asia/Kolkata'?'selected':''?>>Asia/Kolkata</option><option value="UTC" <?=$s['timezone']==='UTC'?'selected':''?>>UTC</option><option value="Asia/Dubai" <?=$s['timezone']==='Asia/Dubai'?'selected':''?>>Asia/Dubai</option></select></label><label style="grid-column:1/-1">Address<textarea name="address" rows="3"><?=e($s['address'])?></textarea></label><div style="grid-column:1/-1;display:flex;justify-content:flex-end;gap:.75rem"><a class="btn btn-secondary" href="/admin/index.php">Cancel</a><button class="btn btn-primary" type="submit">Save Settings</button></div></form></section></main></div></div><script src="/assets/js/main.js"></script><script src="/assets/js/dashboard.js"></script></body></html>
